=== DetrembleurArthur/geode/resources/geode.dtd
<?xml version='1.0' encoding='UTF-8'?>
        <!ELEMENT geode (servers|clients|udp-handlers)*>
        <!ELEMENT servers (server)*>
        <!ELEMENT server (protocols)*>
        <!ATTLIST server
                id CDATA "default"
                ip CDATA "0.0.0.0"
                backlog CDATA "50"
                port CDATA "5785">
        <!ELEMENT protocols (protocol)*>
        <!ELEMENT protocol (#PCDATA)>
        <!ATTLIST protocol
                class CDATA #REQUIRED>
        <!ELEMENT clients (client)*>
        <!ELEMENT client (#PCDATA)>
        <!ATTLIST client
                id CDATA "default"
                server-ip CDATA "0.0.0.0"
                server-port CDATA "5785"
                protocol CDATA #REQUIRED>
        <!ELEMENT udp-handlers (udp-handler)*>
        <!ELEMENT udp-handler (#PCDATA)>
        <!ATTLIST udp-handler
                id CDATA "default"
                host CDATA "127.0.0.1"
                port CDATA "5786"
                bind CDATA "false">

=== DetrembleurArthur/geode/resources/geode.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE geode SYSTEM "geode.dtd" >
<geode>
    <servers>
        <server id="MyServer" ip="127.0.0.1" port="50000" backlog="50">
            <protocols>
                <protocol class="MainSRV"/>
            </protocols>
        </server>
    </servers>
    <clients>
        <client id="MyClient" server-ip="127.0.0.1" server-port="50000" protocol="MainCLI"/>
        <client id="Producer" server-ip="127.0.0.1" server-port="50000" protocol="Producer"/>
    </clients>
</geode>
